version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    # env_file:
    #   - .env_backend
    networks:
      - internal
    depends_on:
      - db
    volumes:
      # Monte le dossier de logs de l'hôte vers /app/logs dans le conteneur
      - ./backend/logs:/app/logs
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - internal
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init/:/docker-entrypoint-initdb.d/
    networks:
      - internal
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      - images_data:/srv
      - filebrowser_database:/database
      - filebrowser_config:/config
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge

volumes:
  db_data:
  images_data:
  filebrowser_database:
  filebrowser_config:





# t3.medium , 4 Go RAM , 20–30 GB stockage 